image: archlinux
secrets:
- da1f93b4-c155-406b-9efd-75d9c8d41454
packages:
  - go
sources:
  - https://github.com/go-ap/storage
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd storage && go mod download
  - tests: |
      cd storage && make test
  - coverage: |
      set -a +x
      cd storage && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @storage.coverprofile \
           -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${STORAGE_TOKEN}&branch=${GIT_BRANCH}&service=custom"
