image: archlinux
packages:
  - go
sources:
  - https://github.com/go-ap/processing
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd processing
      make test
  - coverage: |
      set -a +x
      cd processing && make coverage
